[Hackday] Suporte a mais de um bucket da s3
elo7/harbor pull request #13
Opened 2017-06-13 14:30 UTC by bvieira

🔨 @bvieira
------------------------

# Changelog
- estrutura do projeto para respeitar os padrões do go
- refactory de algumas funcs e visibilidade
- suporte a mais de um bucket do s3
- suporte ao 'shared conf' da aws além de variáveis de ambiente
- script para gerar binário de acordo com `os` e `arch` usando docker

## Dev:
1. [x] Desenvolvido
2. [x] Testado manualmente pelo dev
3. [x] Testes unitários

## Reviewer:
4. [ ] Documentação atualizada
5. [ ] Aprovado na revisão
6. [ ] Testado manualmente pelo revisor

# Tests
## Retrocompatibilidade
- executar com um `harbor.yml` atual
  - [ ] verificar se está se comportando corretamente
## Apenas um bucket
- alterar o `harbor.yml` para usar o formato de `s3repositories.default`
  - [ ]  verificar se apresenta o mesmo comportamento do teste anterior
## Dois buckets
- alterar o `harbor.yml` para ter dois buckets no `s3repositories` e utilizar as configs no `files`
  - [ ] verificar se os arquivos estão sendo baixados corretamente

2017-06-15 17:27 UTC, rsaraiva requested changes

2017-06-15 17:27 UTC, rsaraiva commented on README.md
> + s3repositories: #support after version 0.3, map of string and s3 repository
Faltou colocar isso no main.go para aparecer no `harbor --help`

2017-06-15 17:27 UTC, rsaraiva commented on README.md
> +     repository: <[optional] s3 repository used, default 'default'>
aqui tbm.

2017-06-15 17:27 UTC, rsaraiva commented on README.md
>     basepath: <inside the bucket the root path for files to be downloaded>
Seria legal indicar que esse cara também é opcional.

2017-06-15 17:58 UTC, rsaraiva commented
Seria legal atualizar o job http://jenkins.vpc.elo7aws.com.br:8080/job/harbor-release para utilizar o novo script que você criou.

2017-06-15 19:07 UTC, bvieira commented on README.md
>     basepath: <inside the bucket the root path for files to be downloaded>
done!

2017-06-15 19:07 UTC, bvieira commented on README.md
> + s3repositories: #support after version 0.3, map of string and s3 repository
done!

2017-06-15 19:07 UTC, bvieira commented on README.md
> +     repository: <[optional] s3 repository used, default 'default'>
done!

2017-06-20 18:58 UTC, rsaraiva approved these changes

2017-06-20 18:59 UTC, merged